# .github/workflows/ci.yml

name: MLOps Regression Workflow

on:
  push:
    branches:
      - reg_branch
      - hyper_branch # <-- ADD THIS LINE

jobs:
# ... THE REST OF THE FILE STAYS EXACTLY THE SAME ...